In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

def OpenImage(path):
    I = cv2.imread(path)
    if I is None:
        raise FileNotFoundError("")
    L, C = I.shape[:2]
    return I, L, C


In [2]:
def Divide(I):
    if len(I.shape) == 3:
        B, G, R = cv2.split(I)
        return B, G, R

In [3]:
def HSV(I):
    return cv2.cvtColor(I, cv2.COLOR_BGR2HSV)

In [4]:
def CountPix(I):
    L, C = I.shape[:2]
    N = L * C
    return N

In [5]:
def FactPix(I, alpha, beta):
    new_image = cv2.convertScaleAbs(I, alpha=alpha, beta=beta)
    return new_image

In [6]:
def ViewImage(I):
    if I is None:
        print(f"Error: Could not find image at {path}")
        return
    cv2.imshow("My Image Viewer", I)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [7]:
car = cv2.imread('./car.png')

In [8]:
car.shape

(133, 301, 3)

In [9]:
OpenImage('./car.png')

(array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [255, 255, 255]],
 
        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
         [254, 254, 254],
         [255, 255, 255]],
 
        [[254, 254, 254],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [254, 254, 254],
  

In [10]:
Divide(car)

(array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [254, 254, 254, ..., 254, 254, 255],
        [254, 254, 254, ..., 254, 254, 255],
        [254, 254, 254, ..., 254, 254, 255]], shape=(133, 301), dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [254, 254, 254, ..., 254, 254, 255],
        [254, 254, 254, ..., 254, 254, 255],
        [254, 254, 254, ..., 254, 254, 255]], shape=(133, 301), dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [254, 254, 254, ..., 254, 254, 255],
        [254, 254, 254, ..., 254, 254, 255],
        [254, 254, 254, ..., 254, 254, 255]], shape=(133, 301), dtype=uint8))

In [ ]:
ViewImage(HSV(car))

In [12]:
CountPix(car)

40033

In [15]:
ViewImage(FactPix(car,0.8,0.1))